# This is a basic workflow to help you get started with Actions

name: ManualWorkflow

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
  cloud: test-cloud

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, My First Manual Workflow!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script to see all variable values
        run: |
          echo CLOUD : $cloud,
          echo repository : ${{github.repository}},
          echo workflow : ${{github.workflow}},
          echo triggering_actor : ${{github.triggering_actor}},
          echo MY_ENV_VAR : ${{vars.MY_ENV_VAR}},
          echo MY_ENV_SECRET : ${{vars.MY_ENV_SECRET}},
          echo CODESPACE_SECRET : ${{vars.CODESPACE_SECRET}},
          echo DEPENDABOT_SECRET : ${{vars.DEPENDABOT_SECRET}},
          echo test, and deploy your project.
